### ISSUE TITLE
peerDep failures

### ISSUE THREAD

**Issue by johnmarty** [yoshuawuyts/generator-grunt#1]
I get the following when installing this generator.

npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.4 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-mocha@0.1.6 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9

**Comment by yoshuawuyts** [comment]
Hey! I'm no longer supporting this package since I'm using Gulp nowadays. Your best bet is to roll your own grunt config, or switch over to Gulp.

If you have any problems configuring Karma, your best bet is the [karma documentation](http://karma-runner.github.io/0.12/index.html) (although I'd recommend using webdriver-js instead).

I'll add a note in the README that I'm no longer maintaining this. If you'd like to take over I can add you as a maintainer.
